source "https://rubygems.org"

# Quote from: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll
# Jekyll is an active open source project that is updated frequently. If the github-pages gem
# on your computer is out of date with the github-pages gem on the GitHub Pages server, 
# your site may look different when built locally than when published on GitHub. 
#
# To avoid this, regularly update the github-pages gem on your computer.

# Therefore all versions are fixed to match with the following website: 
# - https://pages.github.com/versions/

gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do

  # Used to automatically generate the RRS feed
  # - https://github.com/jekyll/jekyll-feed

  gem "jekyll-feed","~> 0.17.0"

  # Used to provide us with the capability to redirect users. 
  # - https://github.com/jekyll/jekyll-redirect-from

  gem "jekyll-redirect-from", "~> 0.16.0"

  # Used to expose metadata of the repository.
  # - https://github.com/jekyll/github-metadata

  gem "jekyll-github-metadata", "~> 2.16.1"

  # Used to generate (meta) tags for search engine optimization (SEO).
  # - https://github.com/jekyll/jekyll-seo-tag
  
  gem "jekyll-seo-tag", "~> 2.1"

  # Used to add support for pagination. Especially useful for the next plugin that generates a page for each category.
  # - https://github.com/jekyll/jekyll-paginate

  gem "jekyll-paginate"

  # Used to generate a page for each category.
  # - https://github.com/field-theory/jekyll-category-pages

  gem "jekyll-category-pages"

  # Used to generate images of various sizes to speed up page loading on mobile phones.
  # - https://github.com/MichaelCurrin/jekyll-resize

  gem "jekyll-resize", git: "https://github.com/MichaelCurrin/jekyll-resize"

  # Used to generate the sub resource integrity (SRI) hash of linked assets.
  # - https://github.com/Garanas/jekyll-sub-resource-integrity-hook

  # gem 'jekyll-subresource-integrity-hook', git: "https://github.com/Garanas/jekyll-subresource-integrity-hook"

  gem 'jekyll-transcode-image-filters', git: "https://github.com/Garanas/jekyll-transcode-image-filters"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
