source "https://rubygems.org"

# Quote from: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll
# Jekyll is an active open source project that is updated frequently. If the github-pages gem
# on your computer is out of date with the github-pages gem on the GitHub Pages server, 
# your site may look different when built locally than when published on GitHub. 
#
# To avoid this, regularly update the github-pages gem on your computer.

# Therefore all versions are fixed to match with the following website: 
# - https://pages.github.com/versions/

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed","~> 0.17.0"
  gem "jekyll-redirect-from", "~> 0.16.0"
  gem "jekyll-github-metadata", "~> 2.16.1"
  gem "jekyll-seo-tag", "~> 2.1"
  gem "jekyll-paginate"
  gem "jekyll-category-pages"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
