name: Jekyll - Minify

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build the website
    uses: ./.github/workflows/jekyll-build.yaml

  minify:
    name: Minify
    needs: [build]
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: src
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            package.json
            package-lock.json
            scripts/*
            config/*
          sparse-checkout-cone-mode: false

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: "build"
          path: "src/_site/"

      # Post process the build

      - name: Post process the build
        run: |
          npm install --clean

          # Minify assets to reduce bundle size
          npm run purge-css
          npm run minify-css
          npm run minify-js
          npm run minify-html

          # Turn the website into a PWA
          npm run workbox-generate

      # Upload artifacts for inspection

      - name: Upload artifact for GitHub pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: "github-pages"
          path: "src/_site/"

      - name: Upload artifact for CI
        uses: actions/upload-artifact@v4
        with:
          name: "build-processed"
          path: "src/_site/"
